# Generated by Django 3.0.7 on 2022-06-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='done_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
